name: temp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  path_provider: ^2.0.15
  dio: ^5.3.1
  retrofit: ^4.0.1
  injectable: ^2.1.2
  get_it: ^7.6.0
  device_preview: ^1.1.0
  styled_widget: ^0.4.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  permission_handler: ^10.4.3

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  http_mock_adapter: ^0.4.4
  mockito: ^5.4.2
  flutter_lints: ^2.0.2


flutter:
  uses-material-design: true